name: Parameterized Build Demo
on:
  workflow_dispatch:
    inputs:
      USERNAME:
        description: 'Enter your name'
        required: true
        default: 'Aishwarya'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print USERNAME parameter
        run: |
          echo "Hello, ${{ github.event.inputs.USERNAME }}"
